version: "3.5"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wp_volume:/var/www/html
    networks:
      inception:
  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    env_file: .env
    volumes:
      - wp_volume:/var/www/html
    networks:
      inception:
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      inception:

volumes:
  wp_volume:
    driver: local
    name: "wp"
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ftanon/data/wp'
  mariadb_volume:
    driver: local
    name: "mariadb"
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ftanon/data/mariadb'

networks:
      inception: