version: "3.5"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    networks:
      inception:

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/html
    networks:
      inception:

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - ./database:/var/lib/mysql
    networks:
      inception:
networks:
  inception: