CREATE DATABASE :MARIADB_DB_NAME;
CREATE USER ':MARIADB_USERNAME'@'%' IDENTIFIED BY ':MARIADB_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO ':MARIADB_USERNAME'@'%' WITH GRANT OPTION;
-- ALTER USER 'root'@'localhost' IDENTIFIED BY ':MARIADB_PASSWORD' ;
FLUSH PRIVILEGES;